"""Aggiunta colonna posizione in Strumento

Revision ID: 31ad5a0eb06a
Revises: c8f645ae77c1
Create Date: 2025-05-08 14:31:46.162274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ad5a0eb06a'
down_revision = 'c8f645ae77c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strumenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posizione', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strumenti', schema=None) as batch_op:
        batch_op.drop_column('posizione')

    # ### end Alembic commands ###
