"""Aggiunta destinazione in tab richieste

Revision ID: 4094cc447e2e
Revises: 31ad5a0eb06a
Create Date: 2025-05-09 11:49:53.460155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4094cc447e2e'
down_revision = '31ad5a0eb06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richieste', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destinazione', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richieste', schema=None) as batch_op:
        batch_op.drop_column('destinazione')

    # ### end Alembic commands ###
