"""Add security question fields to Utente

Revision ID: c8f645ae77c1
Revises: 
Create Date: 2025-05-07 14:02:09.335734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f645ae77c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_domanda', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('q_risposta', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.drop_column('q_risposta')
        batch_op.drop_column('q_domanda')

    # ### end Alembic commands ###
